### PR TITLE
New remapping algo

### PR DESCRIPTION
**Pull request by vovannikov**
It is possible to switch now between the new and the old algorithms, the new one is used by default. Once the new algo is settled proves its robustness, the old is to be removed.

### CODE REVIEW

**Comment by vovannikov** [comment]
> Have you changed anything compared to the version that I removed last week?

In the algo itself - no. It lacked #502.

There is a probability that we would need to reduce `ThresholdLower` to 0.001 or something like that. Moreover, I have a feeling that the cut-off threshold should coincide with it if the cut-off feature is used.

Could you maybe run the 49 particles case before we merge it?

**Comment by peterrum** [comment]
> Could you maybe run the 49 particles case before we merge it?

Seems good. As reference, I run also the old version!

**Comment by peterrum** [comment]
When running the simulation, I got 

> Grains remapped: 27/49

in the initial GT step. Does this make sense!?

**Comment by vovannikov** [comment]
> When running the simulation, I got
> 
> > Grains remapped: 27/49
> 
> in the initial GT step. Does this make sense!?

It depends on the settings? Which one did you use? I run the following and did not have any initial remappings:

```
mpirun ~/development/pf-applications-build/applications/sintering/sintering-3D-generic-scalar \
    --cloud ~/development/pf-applications/applications/sintering/sintering_cloud_examples/49particles.cloud \
    ~/development/pf-applications/applications/sintering/analysis_examples/49particles_delta_min_40.json
```

This is the beginning of the output I get for the run above:
```
Running: /dss/dsshome1/0B/di93net/development/pf-applications-build-experimental/applications/sintering/sintering-3D-generic-scalar /dss/dsshome1/0B/di93net/development/pf-applications-build-experimental/applications/sintering/sintering-3D-generic-scalar --cloud /dss/dsshome1/0B/di93net/development/pf-applications/applications/sintering/sintering_cloud_examples/49particles.cloud /dss/dsshome1/0B/di93net/development/pf-applications/applications/sintering/analysis_examples/49particles_delta_min_40.json
  - deal.II (branch: master; revision: b484371cc4e5a6bf0d7cc9d19b1d5012923b060a; short: b484371cc4)
  - deal.II (branch: new_gt_remap_v2; revision: 16d9f7b287119f1f7d717c97c96bfd6bc9fdcc0d; short: 16d9f7b)


Mode:       cloud
Cloud path: /dss/dsshome1/0B/di93net/development/pf-applications/applications/sintering/sintering_cloud_examples/49particles.cloud

Particles list:
# x,y,z,r
58.2563,154.421,75.7669,30.0706
81.464,179.847,28.7446,29.7148
159.432,25.3744,194.656,26.593
192.036,177.48,170.475,33.1861
32.2738,31.4569,160.865,32.6901
89.3769,117.331,189.648,32.0622
144.81,82.9425,180.128,37.1034
144.073,218.21,175.455,33.3289
134.074,110.981,124.964,27.9853
137.591,228.091,109.48,30.1948
83.481,119.674,32.2967,33.2146
81.4323,87.1428,112.893,32.9174
193.655,204.128,113.118,33.0868
79.7952,60.1535,28.0399,29.8488
31.982,99.4293,205.227,33.4579
30.7587,215.337,176.454,32.2024
129.432,84.4641,71.519,34.3942
31.0773,30.2414,42.7334,32.1297
133.416,32.3855,32.5046,34.2001
192.967,78.6902,74.1482,31.5544
192.619,27.6157,42.2808,28.9488
174.049,71.8166,23.8376,25.3546
184.45,139.715,83.6054,34.2268
137.541,152.537,184.3,30.4074
88.4387,32.3085,80.5788,33.5813
29.6362,89.1056,30.5426,31.2213
87.3973,208.727,83.4405,31.5881
116.631,34.3488,139.759,35.1711
86.9647,151.091,132.53,36.7651
31.0005,47.6509,101.225,31.4522
84.3831,176.343,191.164,30.2966
26.9585,147.052,148.24,28.3574
149.52,165.339,128.458,30.5268
28.748,146.845,28.0466,29.9776
155.412,121.786,29.3432,31.2601
29.4622,105.53,86.9761,29.746
131.032,210.486,30.5807,31.5099
158.359,30.9643,90.6079,32.2136
121.457,156.059,71.751,35.8295
187.387,120.282,145.039,32.1011
180.498,175.505,31.3782,31.8404
101.657,33.3105,204.739,34.5475
187.368,32.2181,145.744,33.0669
86.7117,219.441,145.819,35.1044
29.4669,160.781,203.193,31.2088
30.7679,201.98,49.6653,32.6516
32.9807,196.591,114.136,34.9635
75.3358,68.296,166.209,26.3547
29.4939,90.4352,144.052,31.4879

Input parameters file:
{
    "MatrixBased": "false",
    "GrainCutOffTolerance": "0.00000",
    "Adaptivity": {
        "BottomFractionOfCells": "0.1",
        "MaxRefinementDepth": "1",
        "MinRefinementDepth": "3",
        "RefinementFrequency": "10",
        "TopFractionOfCells": "0.3"
    },
    "Approximation": {
        "FEDegree": "1",
        "NPoints1D": "2",
        "NSubdivisions": "1"
    },
    "Geometry": {
        "BoundaryFactor": "0.5",
        "CustomBoundingBox": "false",
        "DivisionsPerInterface": "3",
        "HangingNodeWeight": "1",
        "InterfaceBufferRatio": "3",
        "InterfaceWidth": "8",
        "MinimizeOrderParameters": "true",
        "Periodic": "false",
        "BoundingBox": {
            "Xmax": "0",
            "Xmin": "0",
            "Ymax": "0",
            "Ymin": "0",
            "Zmax": "0",
            "Zmin": "0"
        }
    },
    "GrainTracker": {
        "BufferDistanceRatio": "0.05",
        "GrainTrackerFrequency": "25",
        "ThresholdLower": "0.01",
        "ThresholdUpper": "1.01"
    },
    "Material": {
        "EnergyAbstract": {
            "A": "4.35",
            "B": "0.15",
            "KappaC": "9.0",
            "KappaP": "1.79"
        },
        "MobilityAbstract": {
            "L": "1",
            "Mgb": "0.4",
            "Msurf": "4",
            "Mvap": "1e-10",
            "Mvol": "0.01"
        },
        "Type": "Abstract"
    },
    "NonLinearData": {
        "LinearRelativeTolerance": 0.01,
        "NewtonUseDamping": true,
        "NonLinearSolverType": "NOX",
        "JacobiFree": false,
        "LinearMaxIterations": 100,
        "NewtonThresholdNewtonIterations": 100,
        "NewtonThresholdLinearIterations": 50,
        "NewtonReusePreconditioner": false
    },
    "Output": {
        "Contour": "true",
        "ContourNCoarseningSteps": "0",
        "Debug": "false",
        "Fields": "bnds",
        "HigherOrderCells": "false",
        "OutputTimeInterval": "500",
        "Regular": "false",
        "VtkPath": ".",
        "MeshOverheadEstimate": false
    },
    "Preconditioners": {
        "OuterPreconditioner": "BlockPreconditioner2",
        "BlockPreconditioner2": {
            "Block0Preconditioner": "ILU",
            "Block1Approximation": "avg",
            "Block1Preconditioner": "BlockILU"
        }
    },
    "Profiling": {
        "OutputTimeInterval": "900",
        "RunVmults": "false",
        "OutputMemoryConsumption": "false"
    },
    "Restart": {
        "Interval": "20000",
        "MaximalOutput": "1",
        "Prefix": "./restart",
        "Type": "simulation_time"
    },
    "TimeIntegration": {
        "IntegrationScheme": "BDF2",
        "DesirableLinearIterations": "100",
        "DesirableNewtonIterations": "5",
        "GrowthFactor": "1.2",
        "TimeEnd": "10",
        "TimeStart": "0",
        "TimeStepInit": "0.1",
        "TimeStepMax": "100",
        "TimeStepMin": "1e-05"
    }
}
Parameters in JSON format:
{
    "GrainCutOffTolerance": "0",
    "MatrixBased": "false",
    "TensorialMobilityGradientOnTheFly": "false",
    "Adaptivity": {
        "BottomFractionOfCells": "0.1",
        "ExtraCoarsening": "false",
        "InterfaceValueMax": "0.95",
        "InterfaceValueMin": "0.05",
        "MaxRefinementDepth": "1",
        "MinRefinementDepth": "3",
        "QualityControl": "false",
        "QualityMin": "0.5",
        "RefinementFrequency": "10",
        "TopFractionOfCells": "0.3"
    },
    "Advection": {
        "Ceq": "1",
        "Cgb": "0.1",
        "Enable": "false",
        "K": "100",
        "Mr": "1",
        "Mt": "1"
    },
    "Approximation": {
        "FEDegree": "1",
        "NPoints1D": "2",
        "NSubdivisions": "1"
    },
    "BoundaryConditions": {
        "Direction": "0",
        "Type": "Domain"
    },
    "Geometry": {
        "BoundaryFactor": "0.5",
        "CustomBoundingBox": "false",
        "CustomDivisions": "false",
        "DivisionsPerInterface": "3",
        "GlobalRefinement": "None",
        "HangingNodeWeight": "1",
        "InterfaceBufferRatio": "3",
        "InterfaceWidth": "8",
        "MaxLevel0DivisionsPerInterface": "1",
        "MaxPrime": "20",
        "MinimizeOrderParameters": "true",
        "Periodic": "false",
        "BoundingBox": {
            "Xmax": "0",
            "Xmin": "0",
            "Ymax": "0",
            "Ymin": "0",
            "Zmax": "0",
            "Zmin": "0"
        },
        "Divisions": {
            "Nx": "0",
            "Ny": "0",
            "Nz": "0"
        }
    },
    "GrainTracker": {
        "BufferDistanceFixed": "0",
        "BufferDistanceRatio": "0.05",
        "FastReassignment": "false",
        "GrainTrackerFrequency": "25",
        "ThresholdLower": "0.01",
        "ThresholdUpper": "1.01",
        "TrackWithQuality": "false",
        "UseOldRemap": "false"
    },
    "Material": {
        "EnergyScale": "1",
        "LengthScale": "1",
        "Temperature": "0:1573, 100:1573",
        "TimeScale": "1",
        "Type": "Abstract",
        "EnergyAbstract": {
            "A": "4.35",
            "B": "0.15",
            "KappaC": "9",
            "KappaP": "1.79"
        },
        "EnergyRealistic": {
            "GrainBoundaryEnergy": "0",
            "SurfaceEnergy": "0"
        },
        "Mechanics": {
            "E": "1",
            "Type": "None",
            "nu": "0.25"
        },
        "MobilityAbstract": {
            "L": "1",
            "Mgb": "0.4",
            "Msurf": "4",
            "Mvap": "1e-10",
            "Mvol": "0.01"
        },
        "MobilityRealistic": {
            "DGb0": "0",
            "DGbMob0": "0",
            "DSurf0": "0",
            "DVap0": "0",
            "DVol0": "0",
            "Omega": "0",
            "QGb": "0",
            "QGbMob": "0",
            "QSurf": "0",
            "QVap": "0",
            "QVol": "0"
        }
    },
    "NonLinearData": {
        "FDMJacobianApproximation": "false",
        "JacobiFree": "false",
        "LinearAbsoluteTolerance": "1e-10",
        "LinearMaxIterations": "100",
        "LinearRelativeTolerance": "0.01",
        "LinearSolver": "GMRES",
        "LinearSolverBicgstabTries": "30",
        "NewtonDoUpdate": "true",
        "NewtonReusePreconditioner": "false",
        "NewtonThresholdLinearIterations": "50",
        "NewtonThresholdNewtonIterations": "100",
        "NewtonUseDamping": "true",
        "NonLinearAbsoluteTolerance": "1e-20",
        "NonLinearMaxIterations": "10",
        "NonLinearRelativeTolerance": "1e-05",
        "NonLinearSolverType": "NOX",
        "Verbosity": "1",
        "GMRESData": {
            "OrthogonalizationStrategy": "classical gram schmidt"
        },
        "NOXData": {
            "DirectionMethod": "Newton",
            "LineSearchInterpolationType": "Cubic",
            "LineSearchMethod": "Full Step",
            "OutputInformation": "0"
        },
        "SNESData": {
            "LineSearchName": "bt",
            "SolverName": "newtonls"
        }
    },
    "Output": {
        "ConcentrationContour": "false",
        "Contour": "true",
        "ContourNCoarseningSteps": "0",
        "ContourTex": "false",
        "Debug": "false",
        "DomainIntegrals": "free_energy, gb_area, solid_vol, surf_area",
        "Fields": "bnds",
        "FluxesDivergences": "false",
        "GrainBoundaries": "false",
        "HigherOrderCells": "false",
        "IsoGrainBoundariesArea": "false",
        "IsoSurfaceArea": "false",
        "MeshOverheadEstimate": "false",
        "OutputTimeInterval": "500",
        "Porosity": "false",
        "Quality": "false",
        "Regular": "false",
        "Shrinkage": "false",
        "Table": "false",
        "UseControlBox": "false",
        "VtkPath": ".",
        "ControlBox": {
            "Xmax": "0",
            "Xmin": "0",
            "Ymax": "0",
            "Ymin": "0",
            "Zmax": "0",
            "Zmin": "0"
        }
    },
    "Preconditioners": {
        "OuterPreconditioner": "BlockPreconditioner2",
        "BlockPreconditioner2": {
            "Block0Preconditioner": "ILU",
            "Block1Approximation": "avg",
            "Block1Preconditioner": "BlockILU",
            "Block2Preconditioner": "AMG",
            "Block2AMG": {
                "NCycles": "5",
                "SmootherSweeps": "4"
            }
        }
    },
    "Profiling": {
        "OutputMemoryConsumption": "false",
        "OutputTimeInterval": "900",
        "RunVmults": "false"
    },
    "Restart": {
        "FlexibleOutput": "false",
        "FullHistory": "true",
        "Interval": "20000",
        "MaximalOutput": "1",
        "Prefix": ".\/restart",
        "Type": "simulation_time"
    },
    "TimeIntegration": {
        "DesirableLinearIterations": "100",
        "DesirableNewtonIterations": "5",
        "GrowthFactor": "1.2",
        "IntegrationScheme": "BDF2",
        "Predictor": "None",
        "SanityCheckPredictor": "false",
        "SanityCheckSolution": "false",
        "TimeEnd": "10",
        "TimeStart": "0",
        "TimeStepInit": "0.1",
        "TimeStepMax": "100",
        "TimeStepMin": "1e-05"
    }
}

Finite element: FE_Q<3>, n_subdivisions = 1
Create subdivided hyperrectangle [265.839200 x 297.277500 x 278.320900] = [-20.545700...245.293500 x -20.440000...276.837500 x -20.482700...257.838200] 
with 5 refinements (global = 0, delayed = 5) and 3x4x4 subdivisions

System statistics:
  - n cell:                    48 (min: 0, max: 1)
  - n cell w hanging nodes:    0 (min: 0, max: 0)
  - n cell wo hanging nodes:   48 (min: 0, max: 1)
  - n cell fine batch:         0 (min: 0, max: 0)
  - n levels:                  1
  - n coarse cells:            48
  - n theoretical fine cells:  48
  - n dofs:                    100

Mobility type: scalar

Number of local refinements to be performed: 6
Execute refinement/coarsening:
System statistics:
  - n cell:                    377 (min: 0, max: 8)
  - n cell w hanging nodes:    18 (min: 0, max: 4)
  - n cell wo hanging nodes:   359 (min: 0, max: 8)
  - n cell fine batch:         376 (min: 0, max: 8)
  - n levels:                  2
  - n coarse cells:            48
  - n theoretical fine cells:  288
  - n dofs:                    560
  - n components:              10

Execute refinement/coarsening:
System statistics:
  - n cell:                    2568 (min: 0, max: 8)
  - n cell w hanging nodes:    488 (min: 0, max: 6)
  - n cell wo hanging nodes:   2080 (min: 0, max: 8)
  - n cell fine batch:         2504 (min: 0, max: 8)
  - n levels:                  3
  - n coarse cells:            48
  - n theoretical fine cells:  1728
  - n dofs:                    3238
  - n components:              10

Execute refinement/coarsening:
System statistics:
  - n cell:                    16554 (min: 4, max: 18)
  - n cell w hanging nodes:    4608 (min: 0, max: 16)
  - n cell wo hanging nodes:   11946 (min: 0, max: 16)
  - n cell fine batch:         15984 (min: 0, max: 16)
  - n levels:                  4
  - n coarse cells:            48
  - n theoretical fine cells:  10368
  - n dofs:                    19325
  - n components:              10

Execute refinement/coarsening:
System statistics:
  - n cell:                    101849 (min: 59, max: 74)
  - n cell w hanging nodes:    38428 (min: 0, max: 53)
  - n cell wo hanging nodes:   63421 (min: 13, max: 72)
  - n cell fine batch:         98072 (min: 48, max: 72)
  - n levels:                  5
  - n coarse cells:            48
  - n theoretical fine cells:  62208
  - n dofs:                    116789
  - n components:              10

Execute refinement/coarsening:
System statistics:
  - n cell:                    567888 (min: 362, max: 377)
  - n cell w hanging nodes:    228311 (min: 8, max: 265)
  - n cell wo hanging nodes:   339577 (min: 106, max: 368)
  - n cell fine batch:         542184 (min: 296, max: 376)
  - n levels:                  6
  - n coarse cells:            48
  - n theoretical fine cells:  373248
  - n dofs:                    651660
  - n components:              10

Execute refinement/coarsening:
System statistics:
  - n cell:                    3372599 (min: 2188, max: 2203)
  - n cell w hanging nodes:    1086391 (min: 157, max: 1323)
  - n cell wo hanging nodes:   2286208 (min: 871, max: 2035)
  - n cell fine batch:         3244096 (min: 1928, max: 2200)
  - n levels:                  7
  - n coarse cells:            48
  - n theoretical fine cells:  2239488
  - n dofs:                    3777875
  - n components:              10

Execute grain tracker:
[96mCollisions detected: 0 | has_reassigned_grains = false | has_op_number_changed = false[0m
Grain tracker CPU time = 0.390954 sec
Number of order parameters: 8
Number of grains: 49
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 0
    segment: center = 79.8068 60.2022 27.7904 | radius = 37.5029
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 1
    segment: center = 58.2254 154.378 75.7929 | radius = 37.7343
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 2
    segment: center = 193.134 78.7076 74.1678 | radius = 39.319
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 3
    segment: center = 180.677 175.646 31.2963 | radius = 39.6069
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 4
    segment: center = 137.645 228.228 109.393 | radius = 37.8967
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 5
    segment: center = 32.2287 31.3036 160.946 | radius = 40.4777
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 6
    segment: center = 159.48 25.2349 194.874 | radius = 34.4618
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 7
    segment: center = 89.3213 117.347 189.818 | radius = 39.8535
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 8
    segment: center = 30.654 215.474 176.513 | radius = 39.9423
op_index_current = 0 | op_index_old = 0 | segments = 1 | grain_index = 9
    segment: center = 192.254 177.457 170.63 | radius = 41.0784
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 10
    segment: center = 30.9626 30.0823 42.6883 | radius = 39.9397
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 11
    segment: center = 129.485 84.5033 71.5781 | radius = 42.1303
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 12
    segment: center = 81.4555 179.907 28.5331 | radius = 37.8446
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 13
    segment: center = 32.7683 196.667 114.105 | radius = 42.6263
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 14
    segment: center = 144.861 82.9564 180.246 | radius = 44.7766
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 15
    segment: center = 31.8785 99.3747 205.41 | radius = 41.1871
op_index_current = 1 | op_index_old = 1 | segments = 1 | grain_index = 16
    segment: center = 144.094 218.257 175.588 | radius = 41.115
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 17
    segment: center = 133.42 32.1961 32.3223 | radius = 42.0474
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 18
    segment: center = 83.5128 119.668 32.1063 | radius = 40.9707
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 19
    segment: center = 30.8328 47.5583 101.19 | radius = 39.2315
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 20
    segment: center = 134.107 110.988 124.957 | radius = 35.6449
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 21
    segment: center = 187.508 32.1922 145.726 | radius = 40.7995
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 22
    segment: center = 87.4264 208.98 83.389 | radius = 39.3315
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 23
    segment: center = 193.782 204.251 113.028 | radius = 40.8737
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 24
    segment: center = 101.618 33.224 204.877 | radius = 42.2578
op_index_current = 2 | op_index_old = 2 | segments = 1 | grain_index = 25
    segment: center = 84.425 176.465 191.424 | radius = 38.1331
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 26
    segment: center = 29.4948 89.0441 30.4488 | radius = 38.8999
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 27
    segment: center = 81.4138 87.2047 112.914 | radius = 40.5898
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 28
    segment: center = 184.623 139.663 83.6352 | radius = 41.9362
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 29
    segment: center = 192.847 27.5045 42.2793 | radius = 36.6822
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 30
    segment: center = 30.6455 202.367 49.4048 | radius = 40.6167
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 31
    segment: center = 131.045 210.833 30.4818 | radius = 39.3475
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 32
    segment: center = 137.63 152.495 184.411 | radius = 38.0816
op_index_current = 3 | op_index_old = 3 | segments = 1 | grain_index = 33
    segment: center = 29.4027 160.771 203.295 | radius = 38.9911
op_index_current = 4 | op_index_old = 4 | segments = 1 | grain_index = 34
    segment: center = 174.151 71.8846 23.5812 | radius = 33.0445
op_index_current = 4 | op_index_old = 4 | segments = 1 | grain_index = 35
    segment: center = 88.3842 32.1333 80.5755 | radius = 41.3846
op_index_current = 4 | op_index_old = 4 | segments = 1 | grain_index = 36
    segment: center = 28.5538 146.83 27.9022 | radius = 37.7409
op_index_current = 4 | op_index_old = 4 | segments = 1 | grain_index = 37
    segment: center = 86.9761 151.083 132.545 | radius = 44.4457
op_index_current = 4 | op_index_old = 4 | segments = 1 | grain_index = 38
    segment: center = 187.547 120.218 144.976 | radius = 39.8917
op_index_current = 5 | op_index_old = 5 | segments = 1 | grain_index = 39
    segment: center = 155.391 121.744 29.1601 | radius = 39.0033
op_index_current = 5 | op_index_old = 5 | segments = 1 | grain_index = 40
    segment: center = 116.636 34.1904 139.776 | radius = 42.928
op_index_current = 5 | op_index_old = 5 | segments = 1 | grain_index = 41
    segment: center = 26.8358 146.977 148.318 | radius = 36.091
op_index_current = 5 | op_index_old = 5 | segments = 1 | grain_index = 42
    segment: center = 149.469 165.404 128.445 | radius = 38.1359
op_index_current = 6 | op_index_old = 6 | segments = 1 | grain_index = 43
    segment: center = 121.498 156.095 71.7776 | radius = 43.4661
op_index_current = 6 | op_index_old = 6 | segments = 1 | grain_index = 44
    segment: center = 158.364 30.7849 90.6541 | radius = 39.8775
op_index_current = 6 | op_index_old = 6 | segments = 1 | grain_index = 45
    segment: center = 29.3753 105.571 86.9468 | radius = 37.4655
op_index_current = 6 | op_index_old = 6 | segments = 1 | grain_index = 46
    segment: center = 86.7175 219.621 145.817 | radius = 42.8987
op_index_current = 6 | op_index_old = 6 | segments = 1 | grain_index = 47
    segment: center = 75.3405 68.2924 166.212 | radius = 34.0395
op_index_current = 7 | op_index_old = 7 | segments = 1 | grain_index = 48
    segment: center = 29.3356 90.5301 144.066 | radius = 39.2287

Outputing data at t = 0 (./contour_solution.0.vtu)

it      res_abs      res_rel   ch_rel_abs   ch_res_rel   ac_rel_abs   ac_res_rel  mec_rel_abs  mec_res_rel  linear_iter
 0 1.256335e+03 ------------ 1.415559e-12 ------------ 2.546375e+02 ------------ 0.000000e+00 ------------            0

Create sparsity pattern (cahn_hilliard_op) with:
 - NNZ: 415381540


Create block sparsity pattern (allen_cahn_op) with:
 - number of blocks: 1
 - NNZ:              103845385

 1 3.246215e+01 2.583878e-02 4.182698e+01 2.954802e+13 9.819648e-01 3.856324e-03 0.000000e+00 0.000000e+00            6
 2 5.686370e-01 4.526159e-04 5.839646e-01 4.125328e+11 1.562066e-02 6.134470e-05 0.000000e+00 0.000000e+00            6
 3 6.284641e-03 5.002363e-06 5.363215e-03 3.788760e+09 1.859931e-04 7.304230e-07 0.000000e+00 0.000000e+00            8

t = 0, t_n = 0, dt = 0.1: solved in 3 Newton iterations and 20 linear iterations
[32mIncreasing timestep, dt = 0.12[0m

it      res_abs      res_rel   ch_rel_abs   ch_res_rel   ac_rel_abs   ac_res_rel  mec_rel_abs  mec_res_rel  linear_iter
 0 5.400855e+02 ------------ 6.507324e+02 ------------ 2.827826e+02 ------------ 0.000000e+00 ------------            0
 1 1.551045e+01 2.871850e-02 1.961051e+01 3.013605e-02 7.751903e-01 2.741294e-03 0.000000e+00 0.000000e+00            5
 2 3.806897e-01 7.048694e-04 3.121023e-01 4.796170e-04 1.465071e-02 5.180907e-05 0.000000e+00 0.000000e+00            5
 3 4.002053e-03 7.410035e-06 2.247778e-03 3.454228e-06 2.401751e-04 8.493274e-07 0.000000e+00 0.000000e+00            9

```

**Comment by peterrum** [comment]
Might this be the reason?
```diff
30c21
<         "InterfaceBufferRatio": "1",
---
>         "InterfaceBufferRatio": "3",
90c81
```

**Comment by vovannikov** [comment]
> Might this be the reason?
> 
> ```diff
> 30c21
> <         "InterfaceBufferRatio": "1",
> ---
> >         "InterfaceBufferRatio": "3",
> 90c81
> ```

Yep, as discussed in #469.

**Comment by vovannikov** [comment]
I've run the 49 particles case up to 100,000 seconds (2 grains only left) and did not observe any issues.

**Comment by vovannikov** [comment]
I've run the 49 particles case up to 100,000 seconds (2 grains only left) and did not observe any issues.

**Comment by vovannikov** [comment]
The test runs for the 49 particles have completed and the new algorithm seems to work and is much faster:

| algo | no. calls | min time | avg time | max time |
|---------|---------|---------|---------|---------|
| remap_new | 27 | 0.05446s | 0.4848s | 0.8137s |
| remap_old | 27 | 2.727s | 2.763s | 5.54s |

[49p_algo_old_run.log](https://github.com/hpsint/hpsint/files/11011481/49p_algo_old_run.log)
[49p_algo_old_solution.log](https://github.com/hpsint/hpsint/files/11011482/49p_algo_old_solution.log)
[49p_algo_new_run.log](https://github.com/hpsint/hpsint/files/11011483/49p_algo_new_run.log)
[49p_algo_new_solution.log](https://github.com/hpsint/hpsint/files/11011484/49p_algo_new_solution.log)

**Review by peterrum — APPROVED** [review]
I have run the 49 particle case. Looks good :+1:  The results are identical!

**Comment by peterrum** [comment]
Looks much better now (543 of 1089 have to be remapped).

Old:
```
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
| Total wallclock time elapsed                                                                                                      |     609.7s    64 |     609.7s |     609.7s   290 |
|                                                                                                                                   |                  |                               |
| Section                                                                                                               | no. calls |   min time  rank |   avg time |   max time  rank |
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
| run_grain_tracker::remap::tracker::remap                                                                              |         1 |     382.6s     0 |     382.7s |     382.7s    30 |
| run_grain_tracker::remap::tracker::remap::alter_dof_values_for_grain                                                  |      1271 |       352s    13 |     368.1s |       381s   150 |
| run_grain_tracker::remap::tracker::remap::resolve_cycles                                                              |         1 |   0.00155s   160 |  0.001845s |  0.002318s    72 |
| run_grain_tracker::setup::tracker::initial_setup                                                                      |         1 |     3.372s   134 |     3.373s |       3.4s     0 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains                                                       |         1 |     3.323s    48 |     3.323s |     3.323s     1 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::distributed_stitching                                |         9 |   0.05667s   178 |   0.07098s |   0.08913s   383 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::distributed_stitching::perform_distributed_stitching |         9 |   0.05654s   178 |   0.07086s |   0.08901s   383 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::run_flooding                                         |         9 |    0.5668s     5 |    0.6108s |    0.6937s   219 |
| run_grain_tracker::setup::tracker::initial_setup::reassign_grains                                                     |         1 |   0.04915s    20 |   0.04951s |   0.07627s     0 |
| run_grain_tracker::setup::tracker::initial_setup::reassign_grains::full_reassignment                                  |         1 |  0.005887s    58 |  0.006006s |  0.006175s   336 |
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
```

New:
```
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
| Total wallclock time elapsed                                                                                                      |     231.9s   204 |     231.9s |     231.9s   322 |
|                                                                                                                                   |                  |                               |
| Section                                                                                                               | no. calls |   min time  rank |   avg time |   max time  rank |
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
| run_grain_tracker::remap::tracker::remap                                                                              |         1 |    0.0924s   230 |    0.1832s |    0.2697s   178 |
| run_grain_tracker::setup::tracker::initial_setup                                                                      |         1 |     3.356s    68 |     3.356s |     3.384s     0 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains                                                       |         1 |     3.307s   345 |     3.307s |     3.308s   340 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::distributed_stitching                                |         9 |   0.06041s   262 |   0.07133s |   0.09328s   383 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::distributed_stitching::perform_distributed_stitching |         9 |    0.0603s   262 |   0.07122s |   0.09316s   383 |
| run_grain_tracker::setup::tracker::initial_setup::detect_grains::run_flooding                                         |         9 |    0.5569s   104 |    0.6091s |    0.6633s   331 |
| run_grain_tracker::setup::tracker::initial_setup::reassign_grains                                                     |         1 |   0.04786s   340 |   0.04917s |    0.0759s     0 |
| run_grain_tracker::setup::tracker::initial_setup::reassign_grains::full_reassignment                                  |         1 |  0.005866s   340 |  0.005993s |   0.00626s   240 |
+-----------------------------------------------------------------------------------------------------------------------------------+------------------+------------+------------------+
```

**Pull request merged**
